### ISSUE TITLE
Please change all sonar-scala.com links to archive.org

### ISSUE THREAD

**Issue by grepwood** [sonar-scala/website#238]
If sonar-scala.com is a dead project then please consider doing this. Some people are still using the projects developed under this organization. When trying to find more info about sonar-scala, which is imposed on me by my provider's SonarQube server, I found this on the webpage:
![image](https://github.com/sonar-scala/website/assets/4225739/94989fce-e363-416e-8189-30439c0f0de1)
The domain is out of control and is now a hub of online gambling.

**Comment by mwz** [comment]
you can find the old docs here: https://github.com/sonar-scala/website/tree/master/docs
